stages:
- build
- test
- deploy
- review
- dast
- staging
- canary
- production
- performance
- cleanup
#sast:
#  stage: test
#include:
#- template: Auto-DevOps.gitlab-ci.yml


default:
  before_script:
    - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST


compile:
  stage: build
  tags:
    - docker
  image:
    name: harbor.lab.com/library/make:v1.1
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin'
  script:
    - make all
  artifacts:
    paths:
    - bin/facebooc
    untracked: true
    when: on_success
    expire_in: "7 days"



image build:
  stage: build
  tags:
    - lab
  script:
    - pwd; ls
    - docker image build -t "${HARBOR_HOST}/${HARBOR_PROJECT}/fb:${CI_COMMIT_TAG}" -f fb.Dockerfile .
  dependencies:
    - compile


upload to registry:
  stage: test
  tags:
    - lab
  script:
    - docker push "${HARBOR_HOST}/${HARBOR_PROJECT}/fb:${CI_COMMIT_TAG}"


#build-image:
#  stage: build
#  script:
#    - echo "$HARBOR_PROJECT $HARBOR_URL $HARBOR_HOST $HARBOR_PASSWORD"
##    - docker build -t "${HARBOR_HOST}/${HARBOR_PROJECT}/fb:{$CI_COMMIT_TAG}" .
##    - mkdir -p .docker; echo "{\"auths\":{\"${HARBOR_HOST}\":{\"auth\":\"$(echo -n ${HARBOR_USERNAME}:${HARBOR_PASSWORD} | base64)\"}}}" > .docker/config.json
##    - docker tag hello-world:latest harbor.lab.com/library/hello_cicd:test
##    - docker push "${HARBOR_HOST}/${HARBOR_PROJECT}/hello_cicd:test"
#    - docker image build -t "${HARBOR_HOST}/${HARBOR_PROJECT}/fb:${CI_COMMIT_TAG}" .
#    - docker push "${HARBOR_HOST}/${HARBOR_PROJECT}/fb:${CI_COMMIT_TAG}"

#run:
#  stage: staging
#  script:
#    - echo "${CI_COMMIT_TAG}"
#    - docker image ls
#    - docker run -itd -P --name fb harbor.lab.com/library/fb:${CI_COMMIT_TAG}
